-- ==========================================================
-- EXEMPLOS DE DDL: CREATE TABLE
-- ==========================================================

-- 1. Tabela Simples (Cadastro de Clientes)
CREATE TABLE clientes (
    id_cliente    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR2(100) NOT NULL,
    email         VARCHAR2(150),
    data_cadastro DATE DEFAULT SYSDATE,
    PRIMARY KEY (id_cliente)
);

-- 2. Tabela com Constraints e Chave Estrangeira (Pedidos)
CREATE TABLE pedidos (
    id_pedido     NUMBER PRIMARY KEY,
    id_cliente    NUMBER NOT NULL,
    data_pedido   DATE DEFAULT SYSDATE,
    valor_total   NUMBER(10, 2) CHECK (valor_total >= 0),
    status        VARCHAR2(20) DEFAULT 'PENDENTE',
    CONSTRAINT fk_cliente FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
);

-- 3. Tabela com Particionamento Simples (Logs de Sistema)
-- Útil para grandes volumes de dados
CREATE TABLE logs_sistema (
    id_log        NUMBER,
    mensagem      CLOB,
    data_log      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    nivel         VARCHAR2(10) CHECK (nivel IN ('INFO', 'WARN', 'ERROR'))
)
PARTITION BY RANGE (data_log) (
    PARTITION p2025 VALUES LESS THAN (TO_DATE('01/01/2026', 'DD/MM/YYYY')),
    PARTITION p2026 VALUES LESS THAN (MAXVALUE)
);

-- 4. Tabela Temporária (Global Temporary Table)
-- Os dados persistem apenas durante a sessão ou transação
CREATE GLOBAL TEMPORARY TABLE temp_processamento (
    id_sessao   NUMBER,
    valor_temp  NUMBER
) ON COMMIT PRESERVE ROWS;
